#!/usr/bin/env python3
"""Checks a rendered HTML page before anyone opens it.

The pages are generated by string building, so a missing `>` or an unclosed `<div`
scrambles the whole layout without any error. This catches that, and the link mistakes
that have slipped through before.

    python3 scripts/page_check.py triage-reports/*.html

Problems found:
    structure      a tag closed out of order, or left open at the end of the page
    charset        the page does not declare utf-8 first (every mark renders as mojibake)
    link           an href that is empty, javascript:, http:// or has spaces or quotes in it
    target         an external link that opens in a new tab without rel="noopener"
    query link     a metrics-tool link in the old shape (a `left=` pane with the query in a
                   separate `expr=` parameter), which opens an empty query over the last hour
    id             an in-page link (#x) with no element carrying that id

Used by validate_config.py on every page the shipped results render to.
"""
import re, sys
from html.parser import HTMLParser
from urllib.parse import urlparse, parse_qs

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr",
        # SVG elements the renderers always write self-closed or empty
        "path", "circle", "line", "rect", "polyline", "polygon", "stop", "use"}


class _Page(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.stack, self.problems, self.hrefs, self.ids = [], [], [], set()

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if a.get("id"):
            self.ids.add(a["id"])
        if tag == "a":
            self.hrefs.append((a.get("href"), a.get("target"), a.get("rel") or "", self.getpos()[0]))
        if tag not in VOID:
            self.stack.append((tag, self.getpos()[0]))

    def handle_startendtag(self, tag, attrs):
        a = dict(attrs)
        if a.get("id"):
            self.ids.add(a["id"])

    def handle_endtag(self, tag):
        if tag in VOID:
            return
        if self.stack and self.stack[-1][0] == tag:
            self.stack.pop()
            return
        open_at = next((i for i in range(len(self.stack) - 1, -1, -1) if self.stack[i][0] == tag), None)
        if open_at is None:
            self.problems.append(f"structure: line {self.getpos()[0]}: </{tag}> closes nothing")
        else:
            left = self.stack[open_at + 1:]
            self.problems.append(f"structure: line {self.getpos()[0]}: </{tag}> closes over unclosed "
                                 + ", ".join(f"<{t}> (line {ln})" for t, ln in left))
            del self.stack[open_at:]


def _link_problem(href):
    if href is None or not href.strip():
        return "empty href"
    h = href.strip()
    if h.lower().startswith("javascript:"):
        return f"javascript href {h[:40]}"
    if h.startswith("http://"):
        return f"plain http link {h[:60]}"
    if re.search(r'[\s"<>`]', h):
        return f"href with spaces or quotes {h[:60]}"
    u = urlparse(h)
    q = parse_qs(u.query)
    if "left" in q and "expr" in q:
        return f"query link in the old shape (opens an empty query): {h[:80]}"
    return None


def check(html_text):
    """Problems with one page. Empty means it is fine."""
    p = _Page()
    try:
        p.feed(html_text)
        p.close()
    except Exception as e:  # noqa: BLE001  the parser should never raise, but a page must not crash the gate
        return [f"structure: could not parse ({e})"]
    out = list(p.problems)
    for tag, ln in p.stack:
        if tag not in ("html", "body", "head"):   # the host page may add these around the fragment
            out.append(f"structure: <{tag}> opened at line {ln} is never closed")
    if not html_text.lstrip().lower().startswith(('<meta charset="utf-8">', "<!doctype html><html><head><meta charset=utf8")):
        out.append("charset: the page does not open with a utf-8 declaration")
    for href, target, rel, ln in p.hrefs:
        prob = _link_problem(href)
        if prob:
            out.append(f"link: line {ln}: {prob}")
        elif href.startswith("#") and href[1:] not in p.ids:
            out.append(f"id: line {ln}: {href} points at no element")
        if target == "_blank" and "noopener" not in rel:
            out.append(f"target: line {ln}: new-tab link without rel=noopener")
    return out


def main():
    bad = 0
    for path in sys.argv[1:]:
        with open(path, encoding="utf-8") as f:
            probs = check(f.read())
        print(f"{path}: {'ok' if not probs else str(len(probs)) + ' problem(s)'}")
        for pr in probs:
            print(f"  - {pr}")
        bad += bool(probs)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
